environment:
  matrix:
    - nodejs_version: 10.0.0
    - nodejs_version: 10.1.0
    - nodejs_version: 10.2.0
    - nodejs_version: 10.2.1
    - nodejs_version: 10.3.0
    - nodejs_version: 10.4.0
    - nodejs_version: 10.4.1
    - nodejs_version: 10.5.0
    - nodejs_version: 10.6.0
    - nodejs_version: 10.7.0
    - nodejs_version: 10.8.0
    - nodejs_version: 10.9.0
    - nodejs_version: 9
    - nodejs_version: 8
    - nodejs_version: 7
    - nodejs_version: 6
    - nodejs_version: 5
    - nodejs_version: 4

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test

build: off
